spring.application.name=agendador-tarefas
spring.data.mongodb.uri=mongodb://localhost:27017/db_agendador

usuario.url=localhost:8080
jwt.secret=N2x0QXpFZ1ZrM0p1ZUpTT0JzUllDdXltT3dKMktvT0g=


server.port=8081